# Generated by Django 6.0 on 2025-12-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_item_delete_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
