# Generated by Django 4.2.27 on 2025-12-23 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk_type', models.CharField(choices=[('cow', 'Cow Milk'), ('buffalo', 'Buffalo Milk')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=1, help_text='Quantity in liters', max_digits=4)),
                ('order_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
